### ISSUE TITLE
[Question] How to display new line "\n" in the message?

### ISSUE THREAD

**Issue by hyqshr** [jaredpalmer/nextjs-langchain-example#2]
The newline '\n' is missing in the message streaming. How to keep the newline in streaming?

**Comment by peterdresslar** [comment]
The newline is coming back correctly but getting swallowed up by the unformatted div. Adding 

```className="whitespace-pre-wrap"```

to the inner message div works fine, _a la_ [this fork](https://github.com/peterdresslar/nextjs-langchain-aisdk-example).

Note that if you are at this repo, you might at this point want to check out the [Vercel AI SDK](https://github.com/vercel/ai) since the examples there do what this repo does, but more crystalized.

**Comment by hyqshr** [comment]
> The newline is coming back correctly but getting swallowed up by the unformatted div. Adding
> 
> `className="whitespace-pre-wrap"`
> 
> to the inner message div works fine, _a la_ [this fork](https://github.com/peterdresslar/nextjs-langchain-aisdk-example).
> 
> Note that if you are at this repo, you might at this point want to check out the [Vercel AI SDK](https://github.com/vercel/ai) since the examples there do what this repo does, but more crystalized.

Thank you！

**Comment by peterdresslar** [comment]
Hi there, I know this issue is closed, but I wanted to follow up because the problem is _indeed_ apparently a real issue. It looks like '@microsoft/fetch-event-source' is eating the newlines on the client, per [this issue](https://github.com/Azure/fetch-event-source/issues/50)\.)

I still think people looking at this repo should review the [SDK](sdk.vercel.ai) examples instead, but _for the record_ you can fix the newline problems here with both the className on the jsx and a bit of a hack in the handler that looks like:

```
// page.tsx
try {
    if (stream) {
        await fetchEventSource(`/api/generate`, {
            ..., //headers
            onmessage(ev) {
                //if we receive an empty value for ev, assume it is a newline (and write a newline to the results)
                if (ev.data.length == 0) {
                    setOutput((o) => o + "\n");
                } else {
                    setOutput((o) => o + ev.data);
                }
```
